### PR TITLE
Publish docker images to nexus and dockerhub

### PR DESCRIPTION
**Pull request by JPWKU**
Signed-off-by: Jeremy Phelps <jphelps@linuxfoundation.org>

### CODE REVIEW

**Comment by tsconn23** [comment]
@JPWKU What is "JJB"? I see the new files in this PR in a jjb directory and I notice that the specific verification step has failed. Is that a concern?

**Comment by JPWKU** [comment]
@tsconn23 JJB is Jenkins Job Builder, which is the tool we use to provision all of our Jenkins jobs.  This is the JJB config for publishing artifacts finally.  There are some bugs still to work out, a failed verify on JJB means I have something wrong in it.

**Comment by JPWKU** [comment]
Hmm I just realized we will have issues with this script on Caviums static ARM build machine, but we can go ahead and merge and debug from there.

**Comment by JPWKU** [comment]
@feclare The issue I see with this script is that we can not trust that only a specific build's docker images are the only edgexfoundry docker images on the static build machine.  To get around this I think we can modify the Makefile to interpolate the Jenkins build number into a tag that is generated.  After that I can modify this script to only query for that tag with a specific build number.  Let me think on it a bit.

**Comment by feclare** [comment]
@JPWKU The board used is dedicated to the edgex jenkins jobs. There should not be docker images not generated by edgex.
But I understand the trust issue, anything we can do to help just ask.

**Comment by JPWKU** [comment]
@feclare I submitted a patch on edgex-go that modifies the makefile and gives me specific docker tags I can query for.  I think this will solve the issue.  Consider that two patches are both running builds simultaneously, how can I differentiate the docker images generated?  I think tagging with the SHA of the build solves that issues.

**Comment by JPWKU** [comment]
@feclare as a matter of fact I think we can remove the other tags, but let me get this sorted before I do that.

**Comment by tsconn23** [comment]
@JPWKU "but let me get this sorted before I do that."

Does that mean you want us to wait on merging this PR or is it ready?

**Comment by JPWKU** [comment]
@tsconn23 I have a bit more coming, I'll let you know when it's ready.

**Comment by JPWKU** [comment]
@tsconn23 I think this is ready for merge now.  There are likely still things to work out but we won't know until it starts running.  I'll keep an eye on it after merge.

**Comment by JPWKU** [comment]
We will likely have some race condition on docker tag an docker push on Caviums static machine.  I'm still figuring how to work around that.

**Review by tsconn23 — APPROVED** [review]

**Pull request merged**
