### PR TITLE
Add edinburgh stream for device-mqtt-go.

### PR DESCRIPTION
**Pull request by dweomer**
Signed-off-by: Jacob Blain Christen <jacob.blain.christen@intel.com>

### CODE REVIEW

**Comment by dweomer** [comment]
@edgexfoundry/device-mqtt-go-committers please create the `edinburgh` branch (if you have not already)

**Review by jamesrgregg — DISMISSED** [review]
LGTM

**Comment by lenny-goodell** [comment]
The go.mod file needs to be updated to use go-mod-contracts  0.1.0 before branching.

**Review by anonymouse64 — DISMISSED** [review]
The snap job here looks good to me

**Comment by JPWKU** [comment]
Rebase

**Review by eb-oss — DISMISSED** [review]
Please provide a more descriptive commit message, e.g. "Add edinburgh stream for device-mqtt-go". Also, as @JPWKU mentioned, this needs to be rebased.

**Review by jamesrgregg — DISMISSED** [review]
LGTM

**Review by eb-oss — DISMISSED** [review]

**Review by lranjbar — DISMISSED** [review]
LGTM. Edinburgh branch has been cut for device-mqtt-go

**Review by lranjbar — APPROVED** [review]

**Review by eb-oss — APPROVED** [review]

**Pull request merged**
