### PR TITLE
WIP: Add EdgeX Pipeline template

### PR DESCRIPTION
**Pull request by lranjbar**
This PR is for the WIP on the jenkins pipelines we were demoing in the DevOps working group.

I pushed these pipeline jobs up on the sandbox this morning for inspection. Any review and feedback is helpful for the template. Right now these pipeline jobs won't actually do anything without a Jenkinsfile in go-mod-messaging repo.

Lenny: The go module repos were targeted for these jobs so it is more of a FYI.

Signed-off-by: Lisa Rashidi-Ranjbar <lisa.a.rashidi-ranjbar@intel.com>

### CODE REVIEW

**Review by jamesrgregg — DISMISSED** [review]
LGTM
Nice work @lranjbar

**Review by lenny-goodell — DISMISSED** [review]
LGTM

**Comment by eb-oss** [comment]
This is labeled as a work in progress. Is it ready for review/merge?

**Comment by jamesrgregg** [comment]
@MightyNerdEric. Yes it’s ready and passed all checks with sandbox testing completed as demo’d over the past two weeks

**Comment by lranjbar** [comment]
I'm having a hard time rebasing this branch now.. will recreate in a new PR.

**Pull request closed without merging**
