### PR TITLE
Modify the Jenkins JJB template for volume view #417

### PR DESCRIPTION
**Pull request by vishwassp-hcl-intel**
Signed-off-by: Vishwas SP <vishwasx.s.premachandra@intel.com>

### CODE REVIEW

**Review by jamesrgregg — DISMISSED** [review]

**Review by ernestojeda — DISMISSED** [review]
LGTM.

**Review by jamesrgregg — COMMENTED** [review]
The view is set up on the Sandbox but there's no jobs that show up under it.  @MightyNerdEric may suggest changes to this one.

**Review by eb-oss — CHANGES_REQUESTED** [review]
You'll need to change this. I would suggest:
```
- project:
    name: volume
    view-name: volume
    view-regex: '.*-volume-.*'
    views:
      - common-view
```

**Comment by vishwassp-hcl-intel** [comment]
> You'll need to change this. I would suggest:
> 
> ```
> - project:
>     name: volume
>     view-name: volume
>     view-regex: '.*-volume-.*'
>     views:
>       - common-view
> ```

Updated the code and resubmitted.

**Review by ernestojeda — APPROVED** [review]
👍 Looks good after the changes

**Comment by eb-oss** [comment]
jjb-deploy *edgex-volume*

**Review by eb-oss — APPROVED** [review]

**Pull request merged**
