### PR TITLE
Add doc build jobs for edgex-go

### PR DESCRIPTION
**Pull request by JPWKU**
Signed-off-by: Jeremy Phelps <jphelps@linuxfoundation.org>

### CODE REVIEW

**Comment by tsconn23** [comment]
I'll do a recheck on this to verify, but here's the entry from the log indicating why the JJB step failed:

IOError: [Errno 2] No such file or directory: '../shell/lftools-install.sh'
DEBUG:jenkins_jobs.cache:Cache written out to '/home/jenkins/.cache/jenkins_jobs/cache-host-jobs-https___jenkins_edgexfoundry_org.yml'
Build step 'Execute shell' marked build as failure

**Comment by tsconn23** [comment]
recheck

**Comment by tsconn23** [comment]
Nope, JJB Verify fails right away.

**Comment by JPWKU** [comment]
Ah yeah I'll fix that up

**Comment by JPWKU** [comment]
@tsconn23 I think this is good to merge now...I tested in sandbox.
https://nexus.edgexfoundry.org/content/sites/docs/snapshots/master/16/home/jenkins/16/gopath/src/github.com/edgexfoundry/edgex-go-docs/docs/_build/html/
I'll work on making that url more palatable.

**Comment by JPWKU** [comment]
Ok here is a much better url https://nexus.edgexfoundry.org/content/sites/docs/snapshots/master/18/docs/_build/html/

Note that "18" is the Jenkins build number on PR merges.

**Review by tsconn23 — APPROVED** [review]

**Pull request merged**
