### PR TITLE
Expand rendered image name to include sec and ms

### PR DESCRIPTION
**Pull request by askb**
Expand rendered image name to include seconds and milliseconds.
This reduces the probability of image name collisions on the cloud
from 1/60 to 1/60000.

Fixed upstream in common-packer [1.].

[1.] https://gerrit.linuxfoundation.org/infra/#/c/10986/

https://jira.linuxfoundation.org/browse/RELENG-971

Signed-off-by: Anil Belur <abelur@linuxfoundation.org>

### CODE REVIEW

**Comment by JPWKU** [comment]
@askb Is that Packer verify failure a result of what you are trying to fix?

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
Actually this error makes no sense to me.  ```* unknown configuration key: "instance_name"```
templates/snapcraft.json does not have "instance_name" in it.

**Comment by zxiiro** [comment]
instance_name is a key that's only available in packer 1.2.3 and newer.

**Review by askb — COMMENTED** [review]
any specific reason packer verify is failing?

**Review by JPWKU — APPROVED** [review]
LGTM

**Pull request merged**
