### PR TITLE
Fixes Device SDK Tools JJB

### PR DESCRIPTION
**Pull request by trcox**
Project Generates source code for Device Service from template
Verify and Merge jobs fixed to generate, then run maven build on generated code

Proposed fix, welcome comments and changes

Signed-off-by: Tyler_Cox <Tyler_Cox@dell.com>

### CODE REVIEW

**Comment by tykeal** [comment]
@trcox Things look good. Could you please squash the second change down into the first one though? We generally try to keep any final merge to be the discreet final form instead of an interative commit stream. Unless it actually makes sense to be a full patch series, but that's usually for larger changes so that it's more easily bisectable.

**Review by tykeal — COMMENTED** [review]
This looks good

**Review by tykeal — CHANGES_REQUESTED** [review]
Per my PR comment itself. Could you please squash this down into the other change?

**Comment by trcox** [comment]
@tykeal Squashed!

**Review by tykeal — APPROVED** [review]

**Pull request merged**
