### PR TITLE
Update global-jjb to v0.60.5

### PR DESCRIPTION
**Pull request by eb-oss**
This is needed to fix an issue with python2-pip installation on
CentOS 7 VMs.

Issue-ID: LF-Jira RELENG-3380
Signed-off-by: Eric Ball <eball@linuxfoundation.org>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/edgexfoundry/ci-management/blob/master/.github/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Added labels
## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Sandbox Testing
Test Links :

### CODE REVIEW

**Review by ernestojeda — DISMISSED** [review]
👍🏽

**Comment by eb-oss** [comment]
recheck

**Review by soda480 — DISMISSED** [review]

**Comment by eb-oss** [comment]
Yikes, I didn't realize how out of date this was. We added an update that required a new variable, but I thought I had already applied that to all my projects. In any case, this should pass verification now.

**Comment by eb-oss** [comment]
@ernestojeda @soda480 This needs to be re-reviewed. Thanks!

**Review by soda480 — APPROVED** [review]

**Pull request merged**
