### PR TITLE
Set the value of ISPRIVATE to false for Swagger API docs

### LINKED ISSUE #608: Set default setting to public for Swagger API docs
The current setting is private. Get approval from QA WG will set the default to public.

### PR DESCRIPTION
**Pull request by cherrycl**
Signed-off-by: Cherry Wang <cherry@iotechsys.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/edgexfoundry/ci-management/blob/master/.github/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Added labels
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Documentation content changes
- [ ] Other... Please describe:

## Issue Number: 
Closes: #608 

## Sandbox Testing
Test Links: None

### CODE REVIEW

**Review by jamesrgregg — APPROVED** [review]
LGTM

**Review by ernestojeda — APPROVED** [review]
LGTM

**Comment by cloudxxx8** [comment]
@ernestojeda @jamesrgregg thanks for the approval.  could you please help merge it?

**Comment by cloudxxx8** [comment]
@lranjbar for awareness

**Pull request merged**
