### PR TITLE
Upgrade global-jjb to tip of master 3ae312f 

### PR DESCRIPTION
**Pull request by JPWKU**
Signed-off-by: Jeremy Phelps <jphelps@linuxfoundation.org>

### CODE REVIEW

**Comment by JPWKU** [comment]
This will fix the issue with maven verify jobs not triggering.

**Comment by JPWKU** [comment]
recheck

**Comment by zxiiro** [comment]
typo: upgrade

**Review by zxiiro — CHANGES_REQUESTED** [review]
Upgrade*

**Comment by JPWKU** [comment]
@zxiiro Fixed.

**Review by jwagantall — APPROVED** [review]

**Review by zxiiro — APPROVED** [review]

**Pull request merged**
