### PR TITLE
removing JJB templates due to new GitHub org

### PR DESCRIPTION
**Pull request by ernestojeda**
This PR is one of many needed to remove JJB based pipeline jobs in favor of the new GitHub Organizational job located here: https://jenkins.edgexfoundry.org/job/edgexfoundry/

Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>

### CODE REVIEW

**Comment by ernestojeda** [comment]
I have two open PR's to fix the `app` related jobs.

https://github.com/edgexfoundry/app-service-configurable/pull/42
https://github.com/edgexfoundry/app-functions-sdk-go/pull/265

and edgex-global-pipelines already has a working job:
https://jenkins.edgexfoundry.org/job/edgexfoundry/job/edgex-global-pipelines/

**Comment by ernestojeda** [comment]
recheck

**Comment by eb-oss** [comment]
recheck

**Comment by eb-oss** [comment]
recheck

**Review by jamesrgregg — APPROVED** [review]
LGTM

**Pull request merged**
