### PR TITLE
Remove Fuji Jobs in preperation for Geneva Release

### PR DESCRIPTION
**Pull request by lranjbar**
Signed-off-by: Lisa Rashidi-Ranjbar <lisa.a.rashidi-ranjbar@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/edgexfoundry/ci-management/blob/master/.github/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Added labels
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [X] Other... Please describe:

JJB Template Changes to remove Fuji jobs. In cases where the master branch job is a pipeline the template is removed entirely.

## Sandbox Testing
Test Links :

### CODE REVIEW

**Review by eb-oss — CHANGES_REQUESTED** [review]
The change mostly looks fine. My one big concern is: why leave that stub of the edgex-go job in there? If there are no jobs, there's no reason for a view or the project entry. Why not delete the whole thing?

My other issue here is just that I think the commit message should detail that many of these files are being removed entirely.

**Comment by lranjbar** [comment]
@MightyNerdEric For edgex-go there are some remaining snap jobs that would be in the view/project. We are still in the process of transitioning those jobs to pipelines. I could combine the yaml files for edgex-go this would make it more apparent.

**Comment by eb-oss** [comment]
Now the commit header is too long. :grimacing: Here's what I would suggest:

`Remove Fuji jobs in preparation for Geneva Release

This includes entirely removing the files for several projects that
only had fuji streams.`

**Comment by lranjbar** [comment]
@MightyNerdEric Thanks for the commit message. :) I've updated and rebased

**Review by eb-oss — APPROVED** [review]

**Pull request merged**
