### PR TITLE
Add facility to use a different version of golang

### PR DESCRIPTION
**Pull request by JPWKU**
This patch adds GOROOT with a default.  The user can set it to
any arbitray go installation.

Signed-off-by: Jeremy Phelps <jphelps@linuxfoundation.org>

### CODE REVIEW

**Comment by JPWKU** [comment]
Testing this real quick in sandbox

**Comment by JPWKU** [comment]
Ok looks good in sandbox

**Review by tykeal — COMMENTED** [review]
Why does this keep setting / resetting the PATH? It seems rather weird

**Comment by JPWKU** [comment]
It's a normal step in setting up a golang install.

**Review by tykeal — APPROVED** [review]
That PATH resetting still seems super weird to me, but whatever.

**Pull request merged**
