### PR TITLE
Add device-grove-c jobs

### PR DESCRIPTION
**Pull request by lranjbar**
Signed-off-by: Lisa Rashidi-Ranjbar <lisa.a.rashidi-ranjbar@intel.com>

### CODE REVIEW

**Comment by jamesrgregg** [comment]
@JPWKU @SteveOss we need a reviewer on this one please.

**Review by SteveOss — COMMENTED** [review]
LGTM, but am not an expert on this stuff.

**Comment by JPWKU** [comment]
@lranjbar I think you mentioned this yesterday; Is this only being built for arm architecture?

**Comment by SteveOss** [comment]
@JPWKU To use will need to be built on appropriate system/architecture. But for a CI check, a compile on a single system would probably suffice.

**Comment by lranjbar** [comment]
@JPWKU From what I can tell in the repo - this code is targeting Raspberry PI 3+ (ARM) only. I wasn't sure how this would change the jobs needed in the CI pipeline. This was my first guess.

**Review by jamesrgregg — COMMENTED** [review]
Looks like we need to define where the image will go after build.

**Review by jpwhitemn — DISMISSED** [review]
LGTM

**Comment by lranjbar** [comment]
@jpwhitemn Please review I added the docker push shell script like the other jobs have. thanks!

**Comment by jamesrgregg** [comment]
@MightyNerdEric can you please take a look at this one and approve if all looks good.  Thank you.

**Review by eb-oss — CHANGES_REQUESTED** [review]
Ok, after adding configuration to the Jenkins machines and running some tests, it looks like these jobs are expecting a pom.xml file in the project root. Are there other C builds that use the {verify,merge}-docker-arm jobs? If not, these should be thoroughly tested in the Jenkins sandbox to ensure that they are working as needed.

**Comment by lranjbar** [comment]
@MightyNerdEric Thanks for looking into this! From what I can tell in EdgeX foundry there hasn't been C builds before these. I thought this template might be applicable but turns out it isn't as generic as I thought... back to the drawing board.

**Pull request closed without merging**
