### PR TITLE
Add Ubuntu 1804 arm64 image to Jenkins config

### PR DESCRIPTION
**Pull request by JPWKU**
Signed-off-by: Jeremy Phelps <jphelps@linuxfoundation.org>

### CODE REVIEW

**Review by tykeal — APPROVED** [review]

**Comment by JPWKU** [comment]
hmm looks like the verify job is not configured to trigger off of .cfg changes

**Comment by tykeal** [comment]
@JPWKU I think you're correct. I thought there was a fix that went into global-jjb to deal with that though?

**Comment by JPWKU** [comment]
I don't see it yet, I'd actually like to force merge this PR and circle back.

**Comment by tykeal** [comment]
@JPWKU ok

**Pull request merged**
