### PR TITLE
Add edinburgh stream for app-functions-sdk-go

### PR DESCRIPTION
**Pull request by lenny-goodell**
Add stream for edinburgh release for app-functions-sdk-go
Addresses #386

### CODE REVIEW

**Review by jamesrgregg — CHANGES_REQUESTED** [review]
Please change commit message to imperative mood.
Reference: https://chris.beams.io/posts/git-commit/#imperative

**Comment by lenny-goodell** [comment]
> Please change commit message to imperative mood.
> Reference: https://chris.beams.io/posts/git-commit/#imperative

Done

**Review by jamesrgregg — DISMISSED** [review]
LGTM

**Review by jamesrgregg — APPROVED** [review]
LGTM

**Pull request merged**
