### PR TITLE
add device-sdk-c jjb template

### PR DESCRIPTION
**Pull request by jamesrgregg**
Signed-off-by: James Gregg <james.r.gregg@intel.com>

### CODE REVIEW

**Comment by jamesrgregg** [comment]
@zxiiro thanks for your help.  This one should be ready for an approver.

**Review by SteveOss — APPROVED** [review]
LGTM

**Comment by jamesrgregg** [comment]
@jpwhitemn can we get a review / approval on this one please?

**Review by jpwhitemn — APPROVED** [review]
LGTM

**Comment by jamesrgregg** [comment]
@mightynerderic could you please take a look and approve?

**Comment by eb-oss** [comment]
@jamesrgregg I'm looking into this now, but it looks like our Jenkins build machines don't have cmake installed. Also, the Jenkins system does not appear to have the correct settings file for the stage job.

**Pull request merged**
