### PR TITLE
JJB template for regression test

### PR DESCRIPTION
**Pull request by vishwassp-hcl-intel**
Signed-off-by: Vishwas SP <vishwasx.s.premachandra@intel.com>

### CODE REVIEW

**Review by eb-oss — DISMISSED** [review]
Looks fine to me, but I'd like to see a review by someone more familiar with pipelines, such as @lranjbar or @ernestojeda.

**Review by jamesrgregg — DISMISSED** [review]
LGTM

**Review by ernestojeda — CHANGES_REQUESTED** [review]
Please try to re-use the performance template or incorporate the a lot of these parameters/environment vars into the Jenkinsfile itself

**Comment by vishwassp-hcl-intel** [comment]
> Please try to re-use the performance template or incorporate the a lot of these parameters/environment vars into the Jenkinsfile itself

Updated the JJB for regression-test as per the suggestion.

**Comment by jamesrgregg** [comment]
@ernestojeda please check this again.

**Comment by vishwassp-hcl-intel** [comment]
Now the requested changes are tested and uploaded. Please merge the changes

**Review by jamesrgregg — APPROVED** [review]
LGTM but @ernestojeda needs to check to confirm the changes he requested are present

**Review by lranjbar — APPROVED** [review]
LGTM. I placed a hold tag on this PR because we are waiting for the regression-test repo to be moved out of edgexfoundry-holding

**Comment by vishwassp-hcl-intel** [comment]
As aligned with the team am closing this PR

**Pull request closed without merging**
