### PR TITLE
Update global-jjb to v0.42.0

### PR DESCRIPTION
**Pull request by eb-oss**
This includes adding submodule-disable param to all
lf-infra-github-scm calls.

Signed-off-by: Eric Ball <eball@linuxfoundation.org>

### CODE REVIEW

**Review by jamesrgregg — COMMENTED** [review]
Is there documentation for this change in lf-releng documentation ?
Is this a change that's needed because of a Jenkins plugin that was updated?

**Comment by eb-oss** [comment]
> Is there documentation for this change in lf-releng documentation ?
> Is this a change that's needed because of a Jenkins plugin that was updated?

Yes, there are release notes for every version. We're going from 0.34.0 -> 0.42.0.
This is a change that's needed in general, as it contains a large number of updates and bug fixes. We really should bring in these changes at least once a month, but it has not been updated since March.
Specifically, this was initiated by the failure of the openstack-cron job, detailed here: https://jira.linuxfoundation.org/browse/RELENG-2217
I found that with no other changes, simply updating global-jjb (which comes along with lftools updates as well) fixed the problem.

**Comment by eb-oss** [comment]
Jobs are working as expected (with expected failures when trying to push from the sandbox):
https://jenkins.edgexfoundry.org/sandbox/view/All/job/blackbox-testing-centos7-blackbox-4c-2g-master/
https://jenkins.edgexfoundry.org/sandbox/view/All/job/blackbox-testing-ubuntu18.04-docker-arm64-4c-2g-master/
https://jenkins.edgexfoundry.org/sandbox/view/All/job/ci-management-openstack-cron/
https://jenkins.edgexfoundry.org/sandbox/view/All/job/device-grove-c-master-merge-docker-arm/
https://jenkins.edgexfoundry.org/sandbox/view/All/job/device-grove-c-master-verify-docker-arm/
https://jenkins.edgexfoundry.org/sandbox/view/All/job/edgex-go-master-merge-go/
https://jenkins.edgexfoundry.org/sandbox/view/All/job/edgex-go-master-verify-go/

**Comment by eb-oss** [comment]
Poke for review @jamesrgregg @ernestojeda @lranjbar

**Review by jamesrgregg — APPROVED** [review]
LGTM

**Pull request merged**
