### PR TITLE
first pass at generating multi-architecture docker images

### PR DESCRIPTION
**Pull request by hutchic**
## PR Checklist
Docker image building / creation seems to happen in numerous places. This is a first pass at updating one location to use docker manifests to make multi-architecture images forgoing the buildkit requirement.

pseudocode:
```
docker tag $(REGISTRY)/$(IMAGE):$(ARCH)-$(VERSION)
docker push $(REGISTRY)/$(IMAGE):$(ARCH)-$(VERSION)
docker manifest create $(REGISTRY)/$(IMAGE):$(VERSION)
docker manifest annotate $(REGISTRY)/$(IMAGE):$(VERSION) $(REGISTRY)/$(IMAGE):$(ARCH)-$(VERSION) --os linux --arch $(ARCH)
docker manifest push $(REGISTRY)/$(IMAGE):$(VERSION)
```
end result is `docker run $(REGISTRY)/$(IMAGE):$(VERSION)` will give the proper architecture without needing it explicitly specified

Redis screenshot as an example

image

- [x] The commit message follows our guidelines: https://github.com/edgexfoundry/ci-management/blob/master/.github/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Added labels
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Sandbox Testing
Test Links :

### CODE REVIEW

**Review by eb-oss — COMMENTED** [review]
This script isn't actually being used anywhere that I can see. What's the plan for implementing it? Or is it being run somewhere I can't find in the code?

**Comment by hutchic** [comment]
I believe it's being used:

https://github.com/edgexfoundry/edgex-go/blob/e5ebbe2778b17324c446436c8bb6947fa319c3bf/Jenkinsfile#L37
https://github.com/edgexfoundry/edgex-global-pipelines/blob/4882d0745f735dd1a34cd10f5b43bcfbdc552fb4/vars/edgeXGeneric.groovy#L21

**Comment by hutchic** [comment]
per discussion at security working group although this code path is in use it's deprecated.

**Comment by eb-oss** [comment]
Just to be clear, edgex-global-pipelines/shell is a symlink to global-jjb/shell. It does not link to ci-management/shell. So adding ANY script to this directory in order to have access to it in pipelines would not work.

**Pull request closed without merging**
