### PR TITLE
Rename volume view to edgex-volume

### PR DESCRIPTION
**Pull request by jamesrgregg**
Signed-off-by: James Gregg <james.r.gregg@intel.com>

### CODE REVIEW

**Comment by jamesrgregg** [comment]
Fixes Issue #417

**Comment by eb-oss** [comment]
I'm not sure this will work. A project-view is "^<project-name>-.\*", which means this will not display jobs named "docker-edgex-volume". Either adding the view in edgex-volume.yaml (where it would pick up the project name as defined there) or using a custom view so that it can be defined as "edgex-volume-.*" (without the '^' forcing it to only match at the beginning of the line) might be better solutions.

**Comment by eb-oss** [comment]
jjb-deploy *edgex-volume*

**Comment by jamesrgregg** [comment]
backing out these changes and push differently

**Pull request closed without merging**
