### PR TITLE
Upgrade global jjb to v0.7.0

### PR DESCRIPTION
**Pull request by JPWKU**
JIRA: RELENG-420
Signed-off-by: Jeremy Phelps <jphelps@linuxfoundation.org>

### CODE REVIEW

**Review by zxiiro — DISMISSED** [review]
Typo: Upgrade

**Comment by JPWKU** [comment]
@zxiiro I fixed the type.  Please don't merge yet as I have to make sure `lftools-version` is in place where it needs to be.

**Comment by JPWKU** [comment]
@zxiiro any idea why this doesn't recognize `lftools-version` in defaults.yaml?

**Comment by jwagantall** [comment]
Jeremy, we need to add the same changes in edgex-templates-java.yaml

diff --git a/jjb/edgex-templates-java.yaml b/jjb/edgex-templates-java.yaml
index 17b72a6..fa5e126 100644
--- a/jjb/edgex-templates-java.yaml
+++ b/jjb/edgex-templates-java.yaml
@@ -29,6 +29,7 @@
           project: '{project}'
           branch: '{branch}'
           stream: '{stream}'
+          lftools-version: <1.0.0
 
     wrappers:
       - lf-infra-wrappers:

Thanh confirmed that anything calling lf-infra-parameters needs to add lftools-version to the macro too.

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
@zxiiro this is ready for review

**Review by tykeal — APPROVED** [review]

**Pull request merged**
