### PR TITLE
add edinburgh stream for device-sdk-go

### PR DESCRIPTION
**Pull request by dweomer**
Signed-off-by: Jacob Blain Christen <jacob.blain.christen@intel.com>

### CODE REVIEW

**Review by jamesrgregg — DISMISSED** [review]
LGTM

**Review by lranjbar — DISMISSED** [review]
:+1:

**Review by lranjbar — APPROVED** [review]
Hopefully last rebase needed

**Review by jamesrgregg — COMMENTED** [review]
LGTM still

**Pull request merged**
