### PR TITLE
Add edinburgh stream for device-random-go.

### PR DESCRIPTION
**Pull request by dweomer**
Signed-off-by: Jacob Blain Christen <jacob.blain.christen@intel.com>

### CODE REVIEW

**Comment by dweomer** [comment]
@edgexfoundry/device-random-committers please create the `edinburgh` branch (if you have not already)

**Comment by cloudxxx8** [comment]
I haven't seen edinburgh branch on other repository

**Comment by cloudxxx8** [comment]
@dweomer I just created the edinburgh branch from master on device-random
https://github.com/edgexfoundry/device-random/tree/edinburgh

**Review by eb-oss — DISMISSED** [review]
Please provide a more descriptive commit message, e.g. "Add edinburgh stream for device-random-go"

**Comment by JPWKU** [comment]
Rebase

**Comment by dweomer** [comment]
> Please provide a more descriptive commit message, e.g. "Add edinburgh stream for device-random-go"

done.

**Review by eb-oss — APPROVED** [review]

**Pull request merged**
