### PR TITLE
Add daily release docker jobs for mongo

### PR DESCRIPTION
**Pull request by JPWKU**
Also modify docker template to allow for rulesengine docker job
to still work until we rewrite in golang.

Signed-off-by: Jeremy Phelps <jphelps@linuxfoundation.org>

### CODE REVIEW

**Comment by JPWKU** [comment]
Until we migrate rulesengine from java to go we need to keep this reverse trigger in place.  Jobs that don't have an upstream maven stage job will ignore this trigger.

**Comment by JPWKU** [comment]
The daily release docker template pushes containers to the nexus staging repo 10004 daily as well in anticipation of release.

**Review by eb-oss — APPROVED** [review]

**Comment by lranjbar** [comment]
@JPWKU Will we need this for docker-edgex-volume as well?

**Comment by JPWKU** [comment]
@lranjbar Yes; docker-edgex-volume should just use the same templates and be good to go.

**Pull request merged**
