### PR TITLE
Update all cloud builders to v3 machines

### PR DESCRIPTION
**Pull request by eb-oss**
Since all machines now need a volume, this has been added to the
default config. Smallest builder is not standard-2, so all standard-1
builders have been upgraded.

Issue: LF-Jira RELENG-3670
Signed-off-by: Eric Ball <eball@linuxfoundation.org>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/edgexfoundry/ci-management/blob/master/.github/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Added labels
## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Sandbox Testing
Test Links :

### CODE REVIEW

**Comment by eb-oss** [comment]
v1 nodes are going away, and v3 are both more powerful and cheaper than v2, so all builders have been updated.

**Review by ernestojeda — DISMISSED** [review]

**Comment by eb-oss** [comment]
Not sure what the build issue was here, but this can be considered a WIP until I push the next change. I'm updating the images too, but it also looks like my change to the ARM builders doesn't work. I'm waiting for feedback from Vexx on how to fix that, or if they're continuing to support the old lf-standard builders.

**Comment by eb-oss** [comment]
recheck

**Comment by eb-oss** [comment]
Ok, this is ready for review again. Thanks @ernestojeda !

**Review by ernestojeda — APPROVED** [review]
LGTM

**Pull request merged**
