### PR TITLE
Update blackbox test jobs to remove mongo test

### LINKED ISSUE #610: Remove DATABASE=mongo axis from integration-test
The mongo service is deprecated, also the integration-test execute shell scripts need to update because of the changes in [blackbox-testing#459](https://github.com/edgexfoundry/blackbox-testing/pull/459)

### PR DESCRIPTION
**Pull request by jinlinGuan**
fix https://github.com/edgexfoundry/ci-management/issues/610

Signed-off-by: Ginny Guan <ginny@iotechsys.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/edgexfoundry/ci-management/blob/master/.github/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Added labels
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Issue Number:
#610 
## Sandbox Testing
Test Links :

### CODE REVIEW

**Comment by jinlinGuan** [comment]
The docker engine on Jenkins should update to 18.06.0+(opened a ticket on linuxfoundation to update the docker engine version to 19.03.0+), because the compose file version in [developer-scripts#291](https://github.com/edgexfoundry/developer-scripts/pull/291) is 3.7.

**Comment by jinlinGuan** [comment]
The docker engine version has been updated to 19.03.08
Will change the status to open once [blackbox-testing#459](https://github.com/edgexfoundry/blackbox-testing/pull/459) is merged.

**Review by lenny-goodell — DISMISSED** [review]
LGTM, none of these changes are directly  dependent on my PRs, so this can be merged once the point release is complete.
https://github.com/edgexfoundry/blackbox-testing/pull/459
https://github.com/edgexfoundry/developer-scripts/pull/291

**Comment by lenny-goodell** [comment]
@jinlinGuan , we are ready to move forward with this. Please move out of Draft status. THX!

**Comment by jinlinGuan** [comment]
rebased

**Comment by cloudxxx8** [comment]
@ernestojeda @lenny-intel please help review this PR and it should be able to merged before the multiple docker-compose files PR edgexfoundry/developer-scripts#291

**Review by lenny-goodell — APPROVED** [review]

**Review by ernestojeda — APPROVED** [review]
LGTM

**Pull request merged**
