### PR TITLE
add new app-service-configurable pipeline jjb

### PR DESCRIPTION
**Pull request by ernestojeda**
Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>

### CODE REVIEW

**Comment by ernestojeda** [comment]
Here is the sandbox job for the verify pipeline: https://jenkins.edgexfoundry.org/sandbox/view/All/job/app-service-configurable-verify-pipeline/3/

**Review by lenny-goodell — APPROVED** [review]
LGTM

**Review by lenny-goodell — APPROVED** [review]
LGTM

**Review by eb-oss — APPROVED** [review]

**Review by jamesrgregg — APPROVED** [review]
LGTM
looks simplified

**Pull request merged**
