### PR TITLE
Update integration-test to use Matrix Project

### LINKED ISSUE #344: Run blackbox twice for both Mongo and Redis database
Blackbox tests should verify both Mongo and Redis database.

### PR DESCRIPTION
**Pull request by jinlinGuan**
Fix https://github.com/edgexfoundry/blackbox-testing/issues/344

related: https://github.com/edgexfoundry/blackbox-testing/pull/374

Signed-off-by: Ginny Guan <ginny@iotechsys.com>

### CODE REVIEW

**Comment by cloudxxx8** [comment]
@jinlinGuan please rebase it

**Comment by cloudxxx8** [comment]
@ernestojeda @vishwassp-hcl-intel could you please help review this PR?  It is for the postman blackbox test.

**Comment by jinlinGuan** [comment]
rebased

**Review by vishwassp-hcl-intel — COMMENTED** [review]
LGTM

**Comment by cloudxxx8** [comment]
@jamesrgregg, @vishwassp-hcl-intel has reviewed this PR.  May we merge it?  Thanks.

**Review by eb-oss — APPROVED** [review]

**Comment by eb-oss** [comment]
This needs to be rebased.

**Comment by jinlinGuan** [comment]
rebased

**Pull request merged**
