### PR TITLE
Update CSDK to use Alpine 3.9

### PR DESCRIPTION
**Pull request by iain-anderson**
Signed-off-by: Iain Anderson <iain@iotechsys.com>

### CODE REVIEW

**Review by lranjbar — CHANGES_REQUESTED** [review]
@iain-anderson It might make sense to introduce a simple Makefile in device-sdk-c to run this command and update ci-management to run "make docker". This way you will only have to update the Makefile to update this command in the future. The other repos follow this pattern too.

**Comment by iain-anderson** [comment]
@lranjbar Agreed, will update this PR once the Makefile is in place

**Comment by iain-anderson** [comment]
Updated. The next PR for the csdk edinburgh branch will need to include the toplevel Makefile, else it will not verify.

**Review by jamesrgregg — DISMISSED** [review]
LGTM

**Review by lranjbar — CHANGES_REQUESTED** [review]
@iain-anderson I pushed this on the sandbox and the builds are failing. I'll get back to you in a little bit with some more information to fix it up. The makefile in the repository is good.

**Comment by iain-anderson** [comment]
@lranjbar Have reverted the build file to your solution of using docker directly but with different per-branch settings. Will leave the makefile in the sdk project in place for future.

**Review by lranjbar — APPROVED** [review]

**Comment by lranjbar** [comment]
I tested these on the sandbox here:
https://jenkins.edgexfoundry.org/sandbox/view/All/job/device-sdk-c-master-verify-docker/
https://jenkins.edgexfoundry.org/sandbox/view/All/job/device-sdk-c-edinburgh-verify-docker/

@ernestojeda @jamesrgregg Can one of you double check things? Thanks

**Review by ernestojeda — APPROVED** [review]
LGTM. Thanks Lisa

**Review by jamesrgregg — COMMENTED** [review]
LGTM

**Pull request merged**
