### PR TITLE
Update JJB templates for Fuji Release

### PR DESCRIPTION
**Pull request by soda480**
Update JJB templates for the following:

- device-random
- device-mqtt-go
- device-modbus-go
- device-grove-c
- docker-edgex-mongo

Signed-off-by: Emilio Reyes <emilio.reyes@intel.com>

### CODE REVIEW

**Review by jamesrgregg — DISMISSED** [review]
LGTM

**Review by lranjbar — DISMISSED** [review]
👍

**Comment by lranjbar** [comment]
@soda480 I merged in James PR so this needs a rebase now.

**Comment by soda480** [comment]
@lranjbar ok, the branch has now been rebased with master.

**Review by lranjbar — APPROVED** [review]

**Pull request merged**
