### PR TITLE
Add job for sync api doc to swaggerhub

### PR DESCRIPTION
**Pull request by cherrycl**
1. The [API docs repository](https://github.com/edgexfoundry-holding/edgex-api-docs) put on edgexfoundry-holding (for swagger investigation).
2. The [PR #3](https://github.com/edgexfoundry-holding/edgex-api-docs/pull/3) is opened for sync API docs to swagger
3. This job has to add SwaggerHub API key to credentials for the [Jenkinsfile](https://github.com/cherrycl/edgex-api-docs/blob/fb4379440500f7a89932e8987c2b8c5098fd0ca0/Jenkinsfile#L6).

Signed-off-by: Cherry Wang <cherry@iotechsys.com>

### CODE REVIEW

**Comment by cherrycl** [comment]
The job should be triggered only when API files are changed. I still didn't discover how to detect the changed using Jenkins pipeline. Does anyone have some ideas for it?

**Comment by jamesrgregg** [comment]
> The job should be triggered only when API files are changed. I still didn't discover how to detect the changed using Jenkins pipeline. Does anyone have some ideas for it?

@cherrycl there would have to be a PR to trigger the job.  Common developer workflow should be applicable where a developer submits a PR that needs review.  The API key should be added to Jenkins credential manager and called by an env variable in the Jenkinsfile.  Please let us know when this is planned to move out of holding.

**Review by jamesrgregg — CHANGES_REQUESTED** [review]
The status of this still reads Draft and the repo has not yet moved out of holding. 
Need to address warnings re: branch is out-of-date with the base branch

**Comment by ernestojeda** [comment]
@cherrycl With the rollout of the new GitHub Organization in Jenkins: https://jenkins.edgexfoundry.org/view/EdgeX%20Foundry%20Project/job/edgexfoundry/ this should not be needed anymore. If the repository already has a Jenkinsfile, once it is moved out of edgexfoundry-holding, it will automatically be picked up by Jenkins and builds should start within an hour of the move. So this PR is no longer needed and should be closed. If you would like to keep the changes locally to test on the Jenkins sandbox, that is fine, but this should not be merged.

**Review by ernestojeda — CHANGES_REQUESTED** [review]
@cherrycl With the rollout of the new GitHub Organization in Jenkins: https://jenkins.edgexfoundry.org/view/EdgeX%20Foundry%20Project/job/edgexfoundry/ this should not be needed anymore. If the repository already has a Jenkinsfile, once it is moved out of edgexfoundry-holding, it will automatically be picked up by Jenkins and builds should start within an hour of the move. So this PR is no longer needed and should be closed. If you would like to keep the changes locally to test on the Jenkins sandbox, that is fine, but this should not be merged.

**Comment by cherrycl** [comment]
@jamesrgregg @ernestojeda Thanks for the comments, this PR didn't have to move to holding area. Close this PR.

**Pull request closed without merging**
